package tektonikal.crystalchams;

public enum OptionGroups {
    //TODO: add edge case for the base option
    RENDER,
    VERTICAL_OFFSET,
    ROTATION_SPEED,
    BOUNCE_HEIGHT,
    BOUNCE_SPEED,
    DELAY,
    SCALE,
    LIGHT_LEVEL,
    RENDER_MODE,
    CULLED,
    COLOR,
    OPACITY,
    RAINBOW,
    RAINBOW_SPEED,
    RAINBOW_DELAY,
    RAINBOW_BRIGHTNESS,
    RAINBOW_SATURATION,

    BEAM_RADIUS,

    THE_FUNNY_OPTION,
    THE_FUNNIER_OPTION,

    ANIMATION,

    ANIMATE_VERTICAL_OFFSET,
    STARTING_VERTICAL_OFFSET,
    VERTICAL_OFFSET_ANIMATION_DURATION,
    VERTICAL_OFFSET_ANIMATION_DELAY,
    VERTICAL_OFFSET_EASING,

    ANIMATE_ROTATION_SPEED,
    STARTING_ROTATION_SPEED,
    ROTATION_SPEED_ANIMATION_DURATION,
    ROTATION_SPEED_ANIMATION_DELAY,
    ROTATION_SPEED_EASING,

    ANIMATE_BOUNCE_HEIGHT,
    STARTING_BOUNCE_HEIGHT,
    BOUNCE_HEIGHT_ANIMATION_DURATION,
    BOUNCE_HEIGHT_ANIMATION_DELAY,
    BOUNCE_HEIGHT_EASING,

    ANIMATE_BOUNCE_SPEED,
    STARTING_BOUNCE_SPEED,
    BOUNCE_SPEED_ANIMATION_DURATION,
    BOUNCE_SPEED_ANIMATION_DELAY,
    BOUNCE_SPEED_EASING,

    ANIMATE_TICK_DELAY,
    STARTING_TICK_DELAY,
    TICK_DELAY_ANIMATION_DURATION,
    TICK_DELAY_ANIMATION_DELAY,
    TICK_DELAY_EASING,

    ANIMATE_SCALE,
    STARTING_SCALE,
    SCALE_ANIMATION_DURATION,
    SCALE_ANIMATION_DELAY,
    SCALE_EASING,

    ANIMATE_LIGHT_LEVEL,
    STARTING_LIGHT_LEVEL,
    LIGHT_LEVEL_ANIMATION_DURATION,
    LIGHT_LEVEL_ANIMATION_DELAY,
    LIGHT_LEVEL_EASING,

    ANIMATE_COLOR,
    STARTING_COLOR,
    COLOR_ANIMATION_DURATION,
    COLOR_ANIMATION_DELAY,
    COLOR_EASING,

    ANIMATE_ALPHA,
    STARTING_ALPHA,
    ALPHA_ANIMATION_DURATION,
    ALPHA_ANIMATION_DELAY,
    ALPHA_EASING,

    ANIMATE_RAINBOW_SPEED,
    STARTING_RAINBOW_SPEED,
    RAINBOW_SPEED_ANIMATION_DURATION,
    RAINBOW_SPEED_ANIMATION_DELAY,
    RAINBOW_SPEED_EASING,

    ANIMATE_RAINBOW_DELAY,
    STARTING_RAINBOW_DELAY,
    RAINBOW_DELAY_ANIMATION_DURATION,
    RAINBOW_DELAY_ANIMATION_DELAY,
    RAINBOW_DELAY_EASING,

    ANIMATE_RAINBOW_SATURATION,
    STARTING_RAINBOW_SATURATION,
    RAINBOW_SATURATION_ANIMATION_DURATION,
    RAINBOW_SATURATION_ANIMATION_DELAY,
    RAINBOW_SATURATION_EASING,

    ANIMATE_RAINBOW_BRIGHTNESS,
    STARTING_RAINBOW_BRIGHTNESS,
    RAINBOW_BRIGHTNESS_ANIMATION_DURATION,
    RAINBOW_BRIGHTNESS_ANIMATION_DELAY,
    RAINBOW_BRIGHTNESS_EASING,

    //TODO: add extra things for animating base rotation, beam radius, etc
}
